name: Build Executables for Multiple Platforms

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  # macOS Build Job
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyinstaller

      - name: Build with PyInstaller (macOS)
        run: |
          pyinstaller --onefile --name "ModUpdater" main.py

      - name: Upload Executable (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: ModUpdater-macOS
          path: dist/ModUpdater-macOS

  # Windows Build Job
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build with PyInstaller (Windows)
        run: |
          pyinstaller --onefile --name "ModUpdater.exe" main.py

      - name: Upload Executable (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: ModUpdater-Windows
          path: dist/ModUpdater.exe

  # Optional: Linux Build Job
  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install Python & Dependencies
  #       run: |
  #         python3 -m pip install --upgrade pip
  #         python3 -m pip install pyinstaller

  #     - name: Build with PyInstaller (Linux)
  #       run: |
  #         pyinstaller --onefile --name "ModUpdater" main.py

  #     - name: Upload Executable (Linux)
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ModUpdater-Linux
  #         path: dist/ModUpdater