name: Build Executables for Multiple Platforms

on:
  push:
    tags:
      - "v*"  # Trigger on push to the main branch

jobs:
  # macOS Build Job
  build-macos:
    if: false
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install pyinstaller
          python3 -m pip install -r requirements.txt  # Install all dependencies
          
      - name: Build with PyInstaller (macOS)
        run: |
          source venv/bin/activate
          pyinstaller --onefile --name "ModUpdater" main.py

      - name: Upload Executable (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: ModUpdater-macOS
          path: dist/ModUpdater

  # Windows Build Job
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install -r requirements.txt  # Install all dependencies

      - name: Build with PyInstaller (Windows)
        run: |
          pyinstaller --onefile --name "ModUpdater.exe" main.py

      - name: Upload Executable (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: ModUpdater-Windows
          path: dist/ModUpdater.exe

  # Optional: Linux Build Job
  build-linux:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyinstaller
          python3 -m pip install -r requirements.txt

      - name: Build with PyInstaller (Linux)
        run: |
          pyinstaller --onefile --name "ModUpdaterServer" server.py

      - name: Upload Executable (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: ModUpdaterServer-Linux
          path: dist/ModUpdaterServer

  # GitHub Release Job
  release:
    needs: [build-windows]  # Add build-macos and build-linux if enabled
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: ModUpdater-Windows
          path: artifacts/windows

      # Uncomment below if enabling macOS
      # - name: Download macOS Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ModUpdater-macOS
      #     path: artifacts/macos

      # Uncomment below if enabling Linux
      # - name: Download Linux Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ModUpdaterServer-Linux
      #     path: artifacts/linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows/ModUpdater.exe
            # artifacts/macos/ModUpdater
            # artifacts/linux/ModUpdaterServer
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}