name: Build Executables for Testing

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  # Windows Build Job
  build-windows:
    if: false
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python & Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build with PyInstaller (Windows)
        run: |
          pyinstaller --onefile --name "Test.exe" test.py

      - name: Upload Executable (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: Test-Windows
          path: dist/Test.exe